import sys
import json
import numpy as np
import pandas as pd
from io_utils import load_csv
from binary_logreg import sigmoid
from preprocessing import apply_standardizer, impute_with_train_medians
from predict_report import print_prediction_summary, print_evaluation_report


def parse_args() -> tuple[str, str, str | None]:
	"""Parse CLI args using sys.argv.

	Expected usage:
		python p3/logreg_predict.py <test_csv> <model_file> [truth_csv]
	"""
	if len(sys.argv) not in (3, 4):
		raise SystemExit(
			"Usage: python p3/logreg_predict.py <test_csv> <model_file> [truth_csv]"
		)

	test_csv = sys.argv[1]
	model_file = sys.argv[2]
	truth_csv = sys.argv[3] if len(sys.argv) == 4 else None
	return test_csv, model_file, truth_csv


def load_model(model_file: str) -> dict:
	"""Load model JSON generated by logreg_train.py into a dict."""
	try:
		with open(model_file, "r") as f:
			model = json.load(f)
	except FileNotFoundError as exc:
		raise FileNotFoundError(f"File not found: {model_file}") from exc
	return model


def prepare_test_features(df: pd.DataFrame, model: dict) -> tuple[np.ndarray, int, int]:
	"""Select model features and apply train-time preprocessing params."""
	features = model["features"]

	missing_features = [col for col in features if col not in df.columns]
	if missing_features:
		raise ValueError(f"Missing feature columns in test CSV: {missing_features}")

	X = df[features].copy()
	missing_before = int(X.isna().sum().sum())

	medians = pd.Series(model["train_medians"], index=features)
	means = pd.Series(model["train_means"], index=features)
	stds = pd.Series(model["train_stds"], index=features)

	X = impute_with_train_medians(X, medians)
	missing_after = int(X.isna().sum().sum())
	X = apply_standardizer(X, means, stds)

	return X.to_numpy(dtype=float), missing_before, missing_after


def predict_houses(X_np: np.ndarray, model: dict) -> np.ndarray:
	"""Run one-vs-all prediction and return house names."""
	houses = model["houses"]
	weights = model["weights"]
	bias = model["bias"]

	proba_list = []
	for house in houses:
		w = np.array(weights[house], dtype=float)
		b = float(bias[house])
		z = X_np @ w + b
		p = sigmoid(z)
		proba_list.append(p)

	proba_matrix = np.column_stack(proba_list)
	best_idx = np.argmax(proba_matrix, axis=1)
	predictions = np.array([houses[i] for i in best_idx])
	return predictions


def save_houses_csv(df: pd.DataFrame, predictions: np.ndarray, output_path: str = "houses.csv") -> None:
	"""Save predictions with exact required header: Index,Hogwarts House."""
	if "Index" in df.columns:
		index_values = df["Index"].to_numpy()
	else:
		index_values = np.arange(len(df))

	output = pd.DataFrame({
		"Index": index_values,
		"Hogwarts House": predictions,
	})
	output.to_csv(output_path, index=False)


def evaluate_with_truth(predictions_path: str, truth_csv: str) -> dict:
	"""Build evaluation metrics using Index + Hogwarts House from truth and predictions."""
	pred_df = pd.read_csv(predictions_path)
	truth_df = pd.read_csv(truth_csv)

	required = {"Index", "Hogwarts House"}
	if not required.issubset(pred_df.columns):
		raise ValueError(f"Predictions CSV must contain columns: {required}")
	if not required.issubset(truth_df.columns):
		raise ValueError(f"Truth CSV must contain columns: {required}")

	merged = truth_df[["Index", "Hogwarts House"]].merge(
		pred_df[["Index", "Hogwarts House"]],
		on="Index",
		how="inner",
		suffixes=("_true", "_pred"),
	)

	if merged.empty:
		raise ValueError("No matching Index values between truth and predictions")

	correct = (merged["Hogwarts House_true"] == merged["Hogwarts House_pred"])
	accuracy = float(correct.mean())
	correct_count = int(correct.sum())
	row_count = int(len(merged))

	houses = sorted(set(merged["Hogwarts House_true"]).union(set(merged["Hogwarts House_pred"])))
	cm = pd.crosstab(
		merged["Hogwarts House_true"],
		merged["Hogwarts House_pred"],
		dropna=False,
	).reindex(index=houses, columns=houses, fill_value=0)

	per_house: list[dict] = []
	for house in houses:
		tp = int(cm.loc[house, house])
		fp = int(cm[house].sum() - tp)
		fn = int(cm.loc[house].sum() - tp)
		support = int(cm.loc[house].sum())

		precision = (tp / (tp + fp)) if (tp + fp) > 0 else 0.0
		recall = (tp / (tp + fn)) if (tp + fn) > 0 else 0.0
		f1 = (2.0 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

		per_house.append({
			"house": house,
			"precision": precision,
			"recall": recall,
			"f1": f1,
			"support": support,
		})

	return {
		"accuracy": accuracy,
		"correct": correct_count,
		"rows": row_count,
		"per_house": per_house,
		"confusion_matrix": cm,
	}


def main() -> None:
	test_csv, model_file, truth_csv = parse_args()
	try:
		df = load_csv(test_csv)
	except FileNotFoundError as exc:
		raise SystemExit(f"Error: {exc}") from exc

	try:
		model = load_model(model_file)
	except FileNotFoundError as exc:
		raise SystemExit(f"Error: {exc}") from exc
	X_np, missing_before, missing_after = prepare_test_features(df, model)
	predictions = predict_houses(X_np, model)
	save_houses_csv(df, predictions, "houses.csv")
	pred_series = pd.Series(predictions)
	pred_counts = pred_series.value_counts().sort_index()
	print_prediction_summary(
		test_csv=test_csv,
		n_rows=df.shape[0],
		n_cols=df.shape[1],
		model_file=model_file,
		n_features=len(model["features"]),
		missing_before=missing_before,
		missing_after=missing_after,
		pred_counts=pred_counts,
		n_predictions=len(predictions),
	)

	if truth_csv is not None:
		try:
			report = evaluate_with_truth("houses.csv", truth_csv)
		except FileNotFoundError as exc:
			raise SystemExit(f"Error: File not found: {truth_csv}") from exc
		print_evaluation_report(report)


if __name__ == "__main__":
	main()