import sys
import json
import numpy as np
import pandas as pd
from io_utils import load_csv
from binary_logreg import sigmoid
from preprocessing import apply_standardizer, impute_with_train_medians


def parse_args() -> tuple[str, str]:
	"""Parse CLI args using sys.argv.

	Expected usage:
		python p3/logreg_predict.py <test_csv> <model_file>
	"""
	if len(sys.argv) != 3:
		raise ValueError(
			"Usage: python p3/logreg_predict.py <test_csv> <model_file>"
		)

	test_csv = sys.argv[1]
	model_file = sys.argv[2]
	return test_csv, model_file


def load_model(model_file: str) -> dict:
	"""Load model JSON generated by logreg_train.py into a dict."""
	with open(model_file, "r") as f:
		model = json.load(f)
	return model


def prepare_test_features(df: pd.DataFrame, model: dict) -> tuple[np.ndarray, int, int]:
	"""Select model features and apply train-time preprocessing params."""
	features = model["features"]

	missing_features = [col for col in features if col not in df.columns]
	if missing_features:
		raise ValueError(f"Missing feature columns in test CSV: {missing_features}")

	X = df[features].copy()
	missing_before = int(X.isna().sum().sum())

	medians = pd.Series(model["train_medians"], index=features)
	means = pd.Series(model["train_means"], index=features)
	stds = pd.Series(model["train_stds"], index=features)

	X = impute_with_train_medians(X, medians)
	missing_after = int(X.isna().sum().sum())
	X = apply_standardizer(X, means, stds)

	return X.to_numpy(dtype=float), missing_before, missing_after


def predict_houses(X_np: np.ndarray, model: dict) -> np.ndarray:
	"""Run one-vs-all prediction and return house names."""
	houses = model["houses"]
	weights = model["weights"]
	bias = model["bias"]

	proba_list = []
	for house in houses:
		w = np.array(weights[house], dtype=float)
		b = float(bias[house])
		z = X_np @ w + b
		p = sigmoid(z)
		proba_list.append(p)

	proba_matrix = np.column_stack(proba_list)
	best_idx = np.argmax(proba_matrix, axis=1)
	predictions = np.array([houses[i] for i in best_idx])
	return predictions


def save_houses_csv(df: pd.DataFrame, predictions: np.ndarray, output_path: str = "houses.csv") -> None:
	"""Save predictions with exact required header: Index,Hogwarts House."""
	if "Index" in df.columns:
		index_values = df["Index"].to_numpy()
	else:
		index_values = np.arange(len(df))

	output = pd.DataFrame({
		"Index": index_values,
		"Hogwarts House": predictions,
	})
	output.to_csv(output_path, index=False)


def main() -> None:
	test_csv, model_file = parse_args()
	df = load_csv(test_csv)
	model = load_model(model_file)
	X_np, missing_before, missing_after = prepare_test_features(df, model)
	predictions = predict_houses(X_np, model)
	save_houses_csv(df, predictions, "houses.csv")
	pred_series = pd.Series(predictions)
	pred_counts = pred_series.value_counts().sort_index()

	print(f"Loaded CSV: {test_csv}")
	print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")
	print(f"Loaded model: {model_file}")
	print(f"Selected features: {len(model['features'])}")
	print(f"Missing values (selected features) before imputation: {missing_before}")
	print(f"Missing values (selected features) after imputation:  {missing_after}")
	print("Prediction distribution:")
	for house, count in pred_counts.items():
		print(f"  {house}: {int(count)}")
	print(f"Predictions written to houses.csv ({len(predictions)} rows)")


if __name__ == "__main__":
	main()